CREATE DATABASE FIVEWARE_DB;

USE FIVEWARE_DB;

CREATE TABLE TB_VAGAS(
	
   ID_VAGA BIGINT NOT NULL AUTO_INCREMENT,
   TITULO_VAGA VARCHAR(100) NOT NULL,
   DESC_VAGA VARCHAR(500) NOT NULL,
   PERMITE_CLT INT NOT NULL DEFAULT 0,
   PERMITE_PJ INT NOT NULL DEFAULT 0,
   PERMITE_COOP INT NOT NULL DEFAULT 0,
   TIPO_VAGA VARCHAR(30) NULL DEFAULT '',
   PRAZO_INICIO VARCHAR(50) NULL DEFAULT '',
   
   CONSTRAINT PK_ID_VAGA PRIMARY KEY (ID_VAGA)

);